version: "3.9"
services:
  app:
    build: .
    container_name: SysControl
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "19000:19000" 
      - "19001:19001" 
      - "19002:19002"
      - "8081:8081"
      - "8082:8082" 
    stdin_open: true
    tty: true
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
